INSERT INTO roles(id,name)
SELECT * FROM (SELECT 1,'ROLE_ADMIN') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_ADMIN'
) LIMIT 1;
INSERT INTO roles(id,name)
SELECT * FROM (SELECT 2,'ROLE_USER') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_USER'
) LIMIT 1;
INSERT INTO roles(id,name)
SELECT * FROM (SELECT 3,'ROLE_EMPLOYEE') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_EMPLOYEE'
) LIMIT 1;